remote_theme: morpheus636/hacker-docs-theme
plugins:
- jekyll-remote-theme

title: Morpheus636 Docs
author: Morpheus636

collections:
  contributing:
    output: true
    permalink: /:collection/:path